const movies = [
    "The Godfather",
    "Casablanca",
    "The Dark Knight",
    "Inception",
    "Schindler's List",
    "Pulp Fiction",
    "The Shawshank Redemption",
    "Gone with the Wind",
    "Titanic",
    "Jurassic Park",
    "Star Wars: Episode IV - A New Hope",
    "Avatar",
    "The Matrix",
    "Gladiator",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Silence of the Lambs",
    "Forrest Gump",
    "E.T. the Extra-Terrestrial",
    "The Wizard of Oz",
    "The Sound of Music",
    "Jaws",
    "The Terminator",
    "Indiana Jones and the Raiders of the Lost Ark",
    "The Lion King",
    "A Clockwork Orange",
    "Seven Samurai",
    "The Big Lebowski",
    "Goodfellas",
    "Fight Club",
    "The Usual Suspects",
    "The Departed",
    "A Beautiful Mind",
    "The Princess Bride",
    "The Shining",
    "The Exorcist",
    "The Sixth Sense",
    "The Breakfast Club",
    "Ferris Bueller's Day Off",
    "Back to the Future",
    "Ghostbusters",
    "The Goonies",
    "Die Hard",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "Braveheart",
    "Saving Private Ryan",
    "The Patriot",
    "Troy",
    "The Bourne Identity",
    "The Bourne Supremacy",
    "The Bourne Ultimatum",
    "The Avengers",
    "Avengers: Endgame",
    "Iron Man",
    "Thor",
    "Captain America: The First Avenger",
    "Black Panther",
    "Guardians of the Galaxy",
    "Interstellar",
    "Gravity",
    "The Martian",
    "Arrival",
    "La La Land",
    "Moulin Rouge!",
    "Chicago",
    "The Greatest Showman",
    "12 Years a Slave",
    "Django Unchained",
    "The Hateful Eight",
    "Mad Max: Fury Road",
    "Blade Runner",
    "Terminator 2: Judgment Day",
    "Close Encounters of the Third Kind",
    "Independence Day",
    "Men in Black",
    "The Fifth Element",
    "Blade Runner 2049",
    "The Shape of Water",
    "Whiplash",
    "The Green Mile",
    "The Revenant",
    "The Social Network",
    "The Grand Budapest Hotel",
    "The Dark Knight Rises",
    "The Big Short",
    "Shutter Island",
    "The Wolf of Wall Street",
    "The Prestige",
    "Memento",
    "American Psycho",
    "Se7en",
    "Zodiac",
    "Her",
    "Eternal Sunshine of the Spotless Mind",
    "No Country for Old Men",
    "There Will Be Blood",
    "The Master",
    "Birdman",
    "La La Land",
    "Moonlight",
    "The Shape of Water",
    "Roma",
    "Parasite",
    "The Irishman",
    "Marriage Story",
    "Jojo Rabbit",
    "Joker",
    "Once Upon a Time in Hollywood",
    "1917",
    "Dunkirk",
    "The Hateful Eight",
    "Django Unchained",
    "Inglourious Basterds",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "Reservoir Dogs",
    "Jackie Brown",
    "American History X",
    "A Clockwork Orange",
    "Full Metal Jacket",
    "Apocalypse Now",
    "Platoon",
    "The Deer Hunter",
    "Good Morning, Vietnam",
    "Born on the Fourth of July",
    "Apocalypse Now Redux",
    "The Thin Red Line",
    "Black Hawk Down",
    "Saving Private Ryan",
    "Full Metal Jacket",
    "Hacksaw Ridge",
    "Letters from Iwo Jima",
    "Paths of Glory",
    "Gallipoli",
    "All Quiet on the Western Front",
    "The Hurt Locker",
    "Jarhead",
    "Three Kings",
    "We Were Soldiers",
    "Fury",
    "A Few Good Men",
    "Top Gun",
    "Behind Enemy Lines",
    "Crimson Tide",
    "The Hunt for Red October",
    "Das Boot",
    "Master and Commander: The Far Side of the World",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "The Princess Bride",
    "Stardust",
    "The NeverEnding Story",
    "Labyrinth",
    "The Dark Crystal",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "The Chronicles of Narnia: Prince Caspian",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows – Part 1",
    "Harry Potter and the Deathly Hallows – Part 2",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "Willow",
    "The NeverEnding Story II: The Next Chapter",
    "The Last Unicorn",
    "The Flight of Dragons",
    "The Secret of NIMH",
    "Watership Down",
    "The Land Before Time",
    "An American Tail",
    "The Rescuers",
    "The Great Mouse Detective",
    "The Little Mermaid",
    "Beauty and the Beast",
    "Aladdin",
    "The Lion King",
    "Pocahontas",
    "Mulan",
    "Hercules",
    "Tarzan",
    "The Emperor's New Groove",
    "Atlantis: The Lost Empire",
    "Treasure Planet",
    "Brother Bear",
    "The Incredibles",
    "Ratatouille",
    "WALL-E",
    "Up",
    "Brave",
    "Inside Out",
    "Coco",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Finding Nemo",
    "Finding Dory",
    "Monsters, Inc.",
    "Monsters University",
    "Cars",
    "Cars 2",
    "Cars 3",
    "A Bug's Life",
    "The Good Dinosaur",
    "Shrek",
    "Shrek 2",
    "Shrek the Third",
    "Shrek Forever After",
    "Kung Fu Panda",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "Madagascar",
    "Madagascar: Escape 2 Africa",
    "Madagascar 3: Europe's Most Wanted",
    "Ice Age",
    "Ice Age: The Meltdown",
    "Ice Age: Dawn of the Dinosaurs",
    "Ice Age: Continental Drift",
    "Ice Age: Collision Course",
    "The Adventures of Tintin",
    "Despicable Me",
    "Despicable Me 2",
    "Despicable Me 3",
    "Minions",
    "The Secret Life of Pets",
    "Sing",
    "Moana",
    "Zootopia",
    "Tangled",
    "Frozen",
    "Frozen II",
    "Big Hero 6",
    "Wreck-It Ralph",
    "Ralph Breaks the Internet",
    "The Lego Movie",
    "The Lego Movie 2: The Second Part",
    "How to Train Your Dragon",
    "How to Train Your Dragon 2",
    "How to Train Your Dragon: The Hidden World",
    "Rise of the Guardians",
    "The Book of Life",
    "Ferdinand",
    "Paddington",
    "Paddington 2",
    "The Gruffalo",
    "The Gruffalo's Child",
    "Room on the Broom",
    "Stick Man",
    "Zog",
    "The Highway Rat",
    "The Snail and the Whale",
    "A Christmas Carol",
    "The Polar Express",
    "Arthur Christmas",
    "The Grinch",
    "Elf",
    "Home Alone",
    "Home Alone 2: Lost in New York",
    "The Santa Clause",
    "The Santa Clause 2",
    "The Santa Clause 3: The Escape Clause",
    "A Charlie Brown Christmas",
    "Rudolph the Red-Nosed Reindeer",
    "Frosty the Snowman",
    "The Year Without a Santa Claus",
    "Santa Claus Is Comin' to Town",
    "Jack Frost",
    "Miracle on 34th Street",
    "It's a Wonderful Life",
    "A Christmas Story",
    "National Lampoon's Christmas Vacation",
    "The Muppet Christmas Carol",
    "Elf",
    "Love Actually",
    "Home Alone",
    "The Polar Express",
    "A Charlie Brown Christmas",
    "Rudolph the Red-Nosed Reindeer",
    "Frosty the Snowman",
    "The Year Without a Santa Claus",
    "Santa Claus Is Comin' to Town",
    "How the Grinch Stole Christmas!",
    "It's a Wonderful Life",
    "Miracle on 34th Street"
  ];